# Generated by Django 2.2.1 on 2019-10-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkByMonth',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('uploadDate', models.TextField()),
                ('destDate', models.TextField()),
                ('teacher', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('status', models.BooleanField()),
                ('homeworkId', models.IntegerField()),
                ('mark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Studentsogin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stuId', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherLogin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacherId', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
