# Generated by Django 2.2.1 on 2019-10-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentsogin',
            new_name='StudentLogin',
        ),
        migrations.RenameField(
            model_name='studentlogin',
            old_name='password',
            new_name='pwd',
        ),
        migrations.RenameField(
            model_name='teacherlogin',
            old_name='password',
            new_name='pwd',
        ),
    ]
