# Generated by Django 2.2.1 on 2019-10-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20191029_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollCallDate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RollCallStuDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stuId', models.TextField()),
                ('date', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
