# Generated by Django 2.2.1 on 2019-10-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_rollcalldate_rollcallstudetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stuId', models.TextField()),
                ('stuName', models.TextField()),
                ('stuImg', models.TextField()),
            ],
        ),
    ]
