# Generated by Django 2.2.1 on 2019-11-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_studentinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkdetail',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='homeworkdetail',
            name='status',
        ),
    ]
