# Generated by Django 2.2.1 on 2019-11-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20191107_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkbymonth',
            name='teacherId',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
