# Generated by Django 2.2.1 on 2019-11-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_homeworkbymonth_teacherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherlogin',
            name='teacherName',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
