# Generated by Django 2.2.1 on 2019-11-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_homeworkbymonth_teacherid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUploadInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stuId', models.TextField()),
                ('questionId', models.IntegerField()),
                ('filePath', models.TextField()),
                ('mark', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
