# Generated by Django 2.2.1 on 2019-11-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_teacherlogin_teachername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworkbymonth',
            old_name='teacher',
            new_name='teacherName',
        ),
    ]
