# Generated by Django 2.2.1 on 2019-11-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20191107_2106'),
        ('myApp', '0007_studentuploadinfo'),
    ]

    operations = [
    ]
