# Generated by Django 2.2.1 on 2019-11-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_auto_20191108_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuploadinfo',
            name='status',
            field=models.BooleanField(default=-1),
        ),
    ]
