# Generated by Django 2.2.1 on 2019-11-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_auto_20191108_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuploadinfo',
            name='mark',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='studentuploadinfo',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
